name: Check DataverseConnection NuGet

on:
  workflow_dispatch:

jobs:
  check-nuget:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore DataverseWhoAmI
        run: dotnet restore DataverseWhoAmI/DataverseWhoAmI.csproj

      - name: Build DataverseWhoAmI
        run: dotnet build DataverseWhoAmI/DataverseWhoAmI.csproj --configuration Release --no-restore

      - name: Run DataverseWhoAmI
        run: dotnet run --project DataverseWhoAmI/DataverseWhoAmI.csproj
