name: Check DataverseConnection NuGet

on:
  workflow_dispatch:

jobs:
  check-nuget:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore DataverseWhoAmI
        run: dotnet restore DataverseWhoAmI/DataverseWhoAmI.csproj

      - name: Build DataverseWhoAmI
        run: dotnet build DataverseWhoAmI/DataverseWhoAmI.csproj --configuration Release --no-restore

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run DataverseWhoAmI
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: dotnet run --project DataverseWhoAmI/DataverseWhoAmI.csproj
          env:
            DATAVERSE_URL: ${{ secrets.DATAVERSE_URL }}
