name: PR Validation

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure local-nuget directory exists
        run: mkdir -p local-nuget
        working-directory: ${{ github.workspace }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build DataverseConnection
        run: dotnet build DataverseConnection/DataverseConnection.csproj --configuration Release
        working-directory: ${{ github.workspace }}

      - name: Pack DataverseConnection
        run: dotnet pack DataverseConnection/DataverseConnection.csproj --configuration Release --no-build -o local-nuget
        working-directory: ${{ github.workspace }}

      - name: Show working directory and local-nuget contents
        run: |
          pwd
          ls -l local-nuget
        working-directory: ${{ github.workspace }}

      - name: Restore WhoAmI with local NuGet
        run: dotnet restore DataverseWhoAmI/DataverseWhoAmI.csproj --no-cache --force-evaluate
        working-directory: ${{ github.workspace }}

      - name: Build WhoAmI
        run: dotnet build DataverseWhoAmI/DataverseWhoAmI.csproj --configuration Release --no-restore
        working-directory: ${{ github.workspace }}
