name: PR Validation

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure local-nuget directory exists
        run: mkdir -p local-nuget

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build DataverseConnection
        run: dotnet build DataverseConnection/DataverseConnection.csproj --configuration Release

      - name: Pack DataverseConnection
        run: dotnet pack DataverseConnection/DataverseConnection.csproj --configuration Release --no-build -o local-nuget

      - name: Restore WhoAmI with local NuGet
        run: dotnet restore DataverseWhoAmI/DataverseWhoAmI.csproj

      - name: Build WhoAmI
        run: dotnet build DataverseWhoAmI/DataverseWhoAmI.csproj --configuration Release --no-restore
