name: Publish DataverseConnection NuGet

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure local-nuget directory exists
        run: mkdir -p local-nuget

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore DataverseConnection/DataverseConnection.csproj

      - name: Build
        run: dotnet build DataverseConnection/DataverseConnection.csproj --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack DataverseConnection/DataverseConnection.csproj --configuration Release --no-build -p:PackageVersion=${{ env.VERSION }} -o out

      - name: Publish to nuget.org
        run: dotnet nuget push out/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
